//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mix_View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas_Y_Series
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Urls { get; set; }
        public string Genero { get; set; }
        public string Tipo { get; set; }
    }
}
