//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mix_View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Pass { get; set; }
        public string Gmail { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Genero { get; set; }
    }
}
